### ISSUE TITLE
Changing scope from full <body> to specific <div> or <article>

### ISSUE THREAD

**Issue by shamsmc** [bfiessinger/Easy-TOC#8]
Hi Bastian,

Its not an issue but a feature request.

Currently the script is looking in to all contents inside the <body> tag. But often we have header, footer and contents other than the main contents.

If there is a way to limit the scope to specific article then the script will help developers a lot.

Thanks for the Easy ToC.

**Comment by bfiessinger** [comment]
Hi @shamsmc,

Your request is already featured 

```javascript
let my_toc = new easy_toc( document.querySelector('.my-toc-scope'), {
	...my_options
} );
my_toc.init();
```

`easy_toc` takes the scoped element as it's first argument.
